# Generated by Django 4.0.1 on 2022-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='uploads/logo')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_keyword', models.TextField()),
                ('meta_description', models.TextField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
