# Generated by Django 4.0.1 on 2022-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_slider',
            field=models.BooleanField(default=0),
        ),
    ]
